# JEKYLL BUILD SETUP
exclude:
    - CNAME
    - README
    - LICENSE
    - Gemfile
    - package.json
    - gulfile.js
    - node_modules
    - _dev

destination: ./public_html

# SITE SETUP
title: 	        "Mike Key - mk3y.com"
tagline:        "Musing on Business, Self Improvement, Life and Travel"
description:    "Father. Polymath. Autodidact. I read old books, lift heavy things, eat paleo and drink whiskey."
email:          "mike@mk3y.com"
baseurl:        ""
url:            "https://mk3y.com"

markdown:       kramdown

paginate:       3
paginate_path:  /blog/:num/

permalink:      /:title/

plugins:
  - jekyll-sitemap
  - jekyll-paginate


collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/


 # Custom vars
icon:          "/assets/img/icon.png"
hero:          "/images/bg.jpg"
